formatter: "markdown table"

version: ">= 0.17.0"

sections:
  show:
    - requirements
    - providers
    - inputs
    - outputs
    - resources

content: |-
  {{ .Requirements }}
  {{ .Providers }}
  {{ .Resources }}
  {{ .Inputs }}
  {{ .Outputs }}

output:
  file: "README.md"
  mode: inject

sort:
  enabled: true
  by: required
